fixtures:
  repositories:
    archive:
      repo: "https://github.com/gini/puppet-archive.git"
      ref: "gini-archive-0.2.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.3.2"
    vcsrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
      ref: "1.1.0"
  symlinks:
    drupal: "#{source_dir}"
